using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MusicStore.Entities
{
    public enum Genre
    {

        AcidJazz
        ,
        Acoustic
            ,
        Alternative
            ,
        Ambient
            ,
        Avantgarde
            ,
        Beat
            ,
        Blues
            ,
        Breakbeat
            ,
        Celtic
            ,
        Chanson
            ,
        Chorus
            ,
        Christmas
            ,
        Classical
            ,
        NeoClassical
            ,
        Comedy
            ,
        Country
            ,
        CountryBluegrass
            ,
        CountryCountryRock
            ,
        Dance
            ,
        DancePop
            ,
        Darkwave
            ,
        disco
            ,
        DrumBass
            ,
        EasyListening
            ,
        Electronic
            ,
        ElectronicProgressive
            ,
        Ethnic
            ,
        Experimental
            ,
        Folk
            ,
        African
            ,
        Arabic
            ,
        Asian
            ,
        Balkanian
            ,
        British
            ,
        Bulgarian
            ,
        Chinese
            ,
        FolkRock
            ,
        Georgian
            ,
        Indian
            ,
        Italiano
            ,
        Japan
            ,
        latin
            ,
        MoldavianandRomanian
            ,
        NeoFolk
            ,
        Persia
            ,
        Spanish
            ,
        Tibet
            ,
        funk
            ,
        fusion
            , futurejazz,
        downtempo
            ,
        Goa
            ,
        Gospel
            ,
        Gothic
            ,
        Guitar
            ,
        Hardcore
            ,
        hindinonfilm
            ,
        HipHop
            ,
        House
            , house,
        techno
            ,
        experimental
            ,
        noise
            ,
        Indie
            ,
        indierock
            ,
        indietronic
            ,
        Industrial
            ,
        Instrumental
            ,
        instrumentalpop
            ,
        international
            ,
        Jazz
            ,
        ContemporaryJazz
            ,
        CrossoverJazz
            ,
        EthnicJazz
            ,
        Funk
            ,
        Fusion
            ,
        HardBop
            ,
        JazzPop
            ,
        JazzRock
            ,
        Latin
            ,
        PostBop
            ,
        Jungle
            ,
        krishnacore
            ,
        Flamenco
            ,
        meditative
            ,
        Metal
            ,
        MetalAlternative
            , MetalDeath,
        Black
            ,
        MetalDoom
            ,
        MetalGothic
            ,
        MetalGrindcore
            ,
        MetalHeavy
            ,
        MetalIndustrial
            ,
        MetalPagan
            ,
        MetalPower
            ,
        MetalProgressive
            ,
        MetalSpeed
            ,
        MetalSympho
            ,
        MetalThrash
            ,
        minimal
            ,
        misc
            ,
        Miscellaneous
            ,
        Musical
            ,
        NewAge
            ,
        newage
            ,
        ambient
            ,
        Other
            ,
        Pop
            ,
        poprock
            ,
        PopRock
            ,
        postrock
            ,
        Progressive
            ,
        progressiverock
            ,
        progressivetrance
            ,
        psychedelicrock
            ,
        psychedelictrance
            ,
        psychodelicpostdoom
            ,
        Punk
            ,
        AcidPunk
            ,
        Grunge
            ,
        Soul
            ,
        RnB
            ,
        Rap
            ,
        RapEastCoast
            ,
        RapGangsta
            ,
        RapHipHop
            ,
        Reggae
            ,
        Relaxingmusic
            ,
        Retro
            ,
        Rock
            ,
        RockRoll,
        ComedyRock
            ,
        GarageRock
            ,
        GlamRock
            ,
        Grindcore
            ,
        GuitarVirtuoso
            ,
        HardRock
            ,
        NewWave
            ,
        Psychedelic
            ,
        PunkRock
            ,
        SoftRock
            ,
        Sympho
            ,
        Techno
            ,
        Thrash
            ,
        Urban
            ,
        Ska
            ,
        Soundtrack
            ,
        SoundtrackAnime
            ,
        Space
            ,
        stonerrock
            ,
        symphometal
            ,
        synthpop
            ,
        Tango
            ,
        tangofusion
            ,
        traditional
            ,
        Trance
            ,
        transcendental
            ,
        TripHop
            , triphop
    }
}